name: polaris
label: htex
num_nodes: 1
worker_init: module use /soft/modulefiles; module load conda; conda activate agents;
    cd /lus/eagle/projects/FoundEpidem/bhsu/2024_research/agents/agents/
scheduler_options: '#PBS -l filesystems=home:eagle:grand'
account: FoundEpidem
queue: debug
walltime: '1:00:00'
cpus_per_node: 32
cores_per_worker: 8.0
retries: 0
worker_debug: false
